
version: 2

models:
    - name: game_stats
      description: "A starter dbt model"
      columns:
          - name: username
            description: "The primary key for this table"
            tests:
                - unique
                - not_null